name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GB_TOKEN }}
    
    - name: Github Container Registry:Build and push Docker image
  # You may pin to the exact commit or the version.
  # uses: pmorelli92/github-container-registry-build-push@5e8cb6aa00970646525f2f9361d1cf1c04a26388
      uses: pmorelli92/github-container-registry-build-push@2.0.0
      with:
    # Token such as GITHUB_TOKEN that has `write:packages` scope to authenticate against GCHR.
        github-push-secret: ${{ secrets.GB_TOKEN }}
    # Docker Image name
        docker-image-name: project_imagina
    # Docker Image tag
        docker-image-tag: latest
    # Dockerfile path and name
        dockerfile-path: Dockerfile
    # Path to the build context
        build-context: .
    
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
