name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: imaginaproject.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t imaginaproject.azurecr.io/calamarzo/imagina-project:latest
        docker push imaginaproject.azurecr.io/calamarzo/imagina-project:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'imagina-project'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'imaginaproject.azurecr.io/calamarzo/imagina-project:latest'
