name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/calamarzo/imagina-project:latest
        docker run ghcr.io/calamarzo/imagina-project:latest
        docker push ghcr.io/calamarzo/imagina-project:latest


        
      
      
